build:
    environment:
            php:
                version: 7.0
                ini:
                    'date.timezone': 'US/Pacific'
    dependencies:
        before:
            - cp .env.travis .env
            - touch storage/integration/integration.sqlite
            - mkdir storage/uploads
            - chmod -R 777 storage bootstrap/cache
            - composer install --prefer-source
            - php artisan key:generate
            - php artisan migrate --seed
    tests:
        override:
            -
                command: 'phpunit --no-coverage'
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage:
        timeout: 1200
