build:
    environment:
            php:
                version: 7.0.8
                ini:
                    'date.timezone': 'US/Pacific'
    dependencies:
        before:
            - cp .env.travis .env
            - touch storage/integration/integration.sqlite
            - mkdir storage/uploads
            - chmod -R 777 storage bootstrap/cache
            - composer install --prefer-source
            - php artisan key:generate
            - php artisan migrate --seed
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage: true
        timeout: 1200    # Timeout in seconds.