language: php
php:
  - '7.0'
matrix:
  fast_finish: true
sudo: false
before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
script:
  - touch storage/integration/integration.sqlite
  - mkdir storage/uploads
  - chmod -R 777 storage bootstrap/cache
  - composer self-update
  - composer install --prefer-source
  - php artisan key:generate
  - php artisan migrate --seed
  - phpunit
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/coverage/coverage.xml
