language: php
php:
  - '5.6'
  - '7.0'
matrix:
  fast_finish: true
sudo: false
before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
script:
  - touch storage/acceptance/acceptance.sqlite
  - mkdir storage/uploads
  - chmod -R 777 storage bootstrap/cache
  - composer self-update
  - composer install --prefer-source
  - php artisan key:generate
  - php artisan migrate --seed
  - cp storage/acceptance/acceptance.sqlite storage/integration/integration.sqlite
  - phpunit
